課題15 model spec作成
unochin/sample_app_for_rspec pull request #2
Opened 2019-11-11 12:34 UTC by kiakata

【概要】
- taskモデルのmodel spec作成

【チェックリスト】
- [ ] siderをパスした

【コメント】

2019-11-11 12:48 UTC, kiakata commented on spec/models/task_spec.rb
> +      task1 = user.tasks.create(
task2のvalidationをする前に、同じタイトルのtaskがすでに作成済みである必要があると思い、ここだけ`build`ではなく`create`を使いました。

2019-11-11 13:04 UTC, konumashuri commented on spec/models/task_spec.rb
> +      task1 = user.tasks.create(
必要なければbuildを使ったほうが良いですね！以下詳細です。

createとbuildは仕様上の意味で言うと「データがdbに保存される」か「されないか」です。他にもfactory botに記載したassociationが作られるかなどがありますが大きくはこの2点です。

この2点はパフォーマンスに差ができます。sqlを発行するかしないかの差となります。
buildは発行しなくてcreateはINSERTを発行します。1INSERT目安20~50msくらいかかります。

テストケースが1つだけのときはどちらもほぼ差がないですが、大きなプロジェクトだと1000以上のテストケースとなり比例して発行されるsqlの数も増えます。

テスト時間は短いほうが良いためできればbuildを使ったほうが良いということになります！

2019-11-11 13:11 UTC, shurijoc reviewed
確認をお願いしますー！

2019-11-11 13:11 UTC, konumashuri commented on spec/models/task_spec.rb
> +      task1 = user.tasks.create(
こちらについては表（？）にコメントしました！

2019-11-11 13:11 UTC, konumashuri commented on spec/models/task_spec.rb
> +  let(:user) { FactoryBot.create(:user) }
FactoryBotは省略できますのでその設定をしてみましょう！
https://github.com/thoughtbot/factory_bot/blob/master/GETTING_STARTED.md#rspec

2019-11-11 13:11 UTC, konumashuri commented on spec/models/task_spec.rb
> +      title: 'rspec test',
インデントを整えてくださいー

2019-11-11 13:11 UTC, konumashuri commented on spec/models/task_spec.rb
> +      task = user.tasks.build(
例えば factories/tasks.rbにtask用のfactoryを書いて

```
let(:task) { FactoryBot.build(:task, user: user, title: 'rspec test') } のように書くことができます！
```

2019-11-13 22:17 UTC, kiakata commented on spec/models/task_spec.rb
> +      title: 'rspec test',
修正しました！

2019-11-13 22:18 UTC, kiakata commented on spec/models/task_spec.rb
> +      task = user.tasks.build(
tasks.rbにテスト用のtaskを作成しました！

2019-11-13 22:18 UTC, kiakata commented on spec/models/task_spec.rb
> +  let(:user) { FactoryBot.create(:user) }
設定しました！

2019-11-13 22:19 UTC, kiakata commented on spec/models/task_spec.rb
> +      task1 = user.tasks.create(
丁寧な解説ありがとうございます！

2019-11-13 22:20 UTC, kiakata commented on app/models/task.rb
> +  belongs_to :user
ここはあった方がいいのかな？と思い、加えました。
不要でしたら、ご指摘お願いします。

2019-11-13 22:25 UTC, kiakata commented on spec/factories/tasks.rb
> +    status { 0 }
`association`や`traits`などを使った方が良いのでしょうか？

2019-11-14 04:35 UTC, DaichiSaito reviewed
コメントしました！

2019-11-14 04:35 UTC, DaichiSaito commented on app/models/task.rb
> +  belongs_to :user
つけ忘れでした！つけておいた方が良いですね！

2019-11-14 04:35 UTC, DaichiSaito commented on spec/factories/tasks.rb
> +    status { 0 }
ここで関連付け行って良いと思います！

2019-11-14 05:06 UTC, DaichiSaito commented on spec/models/task_spec.rb
> +        status: 0
このテストケースにおいてstatusを設定する意味ってあるんでしたっけ？？

2019-11-14 11:29 UTC, kiakata commented on spec/models/task_spec.rb
> +        status: 0
無いので消します！

2019-11-14 12:24 UTC, yuji91 commented on spec/models/task_spec.rb
> +      expect(task_2.errors[:title]).to include('has already been taken')
`task_2`よりは`other_task`や`dupulicate_title_task`など意味を伝えられると良いと思います。
task_3, 4, 5など作成された時にそれぞれがどのようなテストデータか分からなると辛いので。

2019-11-14 12:24 UTC, yuji91 requested changes
コメントしました！

2019-11-14 12:32 UTC, yuji91 approved these changes
LGTM!

2019-11-14 12:33 UTC, merged